compile:
  platforms:
    - uno
    - due
    - m4

unittest:
  platforms:
    - uno
  libraries:
    - "OneWire"

packages:
  libraries:
    - source-path: .
      platforms:
        - uno
        - due
        - m4
    - name: OneWire

directories:
  tests: test

aux_libraries:
  - OneWire

dependencies:
  arduino-ci: "~>1.5.0"