compile:
  # Compile tests on multiple Arduino platforms
  platforms:
    - uno          # Standard AVR platform

unittest:
  # Unit test platforms and dependencies
  platforms:
    - uno          # Native host system (Linux in this case)
  libraries:
    - "OneWire"     # Ensure OneWire library is available for testing

# Additional configuration can go here if needed
