name: Arduino CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Create required directories
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          mkdir -p $GITHUB_WORKSPACE/libraries
          mkdir -p $GITHUB_WORKSPACE/.arduino15
          mkdir -p $GITHUB_WORKSPACE/Arduino
      
      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=$GITHUB_WORKSPACE/bin sh
          export PATH="$GITHUB_WORKSPACE/bin:$PATH"
          chmod +x $GITHUB_WORKSPACE/bin/arduino-cli
          arduino-cli version
        env:
          PATH: "$GITHUB_WORKSPACE/bin:${{ env.PATH }}"
      
      - name: Install Arduino cores
        run: |
          $GITHUB_WORKSPACE/bin/arduino-cli core update-index
          $GITHUB_WORKSPACE/bin/arduino-cli core install arduino:avr
        env:
          PATH: "$GITHUB_WORKSPACE/bin:${{ env.PATH }}"
      
      - name: Install OneWire library
        run: |
          $GITHUB_WORKSPACE/bin/arduino-cli lib install OneWire --directory $GITHUB_WORKSPACE/libraries
        env:
          PATH: "$GITHUB_WORKSPACE/bin:${{ env.PATH }}"
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      
      - name: Install Arduino CI
        run: |
          gem install arduino_ci -v 1.6.2
      
      - name: Run Arduino CI Tests
        run: |
          arduino_ci.rb
        env:
          PATH: "$GITHUB_WORKSPACE/bin:${{ env.PATH }}"