name: Arduino CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  runTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y avr-libc
          
      - name: Install Arduino CI
        run: |
          gem install arduino_ci -v 1.5.0
          
      - name: Run Arduino CI Tests
        run: |
          arduino_ci.rb