name: Arduino CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install AVR development files
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-avr avr-libc
      
      - name: Create required directories
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          mkdir -p $GITHUB_WORKSPACE/libraries
          mkdir -p $GITHUB_WORKSPACE/.arduino15
          mkdir -p $GITHUB_WORKSPACE/Arduino

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        
      - name: Configure Arduino CLI
        run: |
          cat > "$GITHUB_WORKSPACE/arduino-cli.yaml" << EOF
          directories:
            data: $GITHUB_WORKSPACE/.arduino15
            downloads: $GITHUB_WORKSPACE/.arduino15/staging
            user: $GITHUB_WORKSPACE/libraries
          board_manager:
            additional_urls: []
          library:
            enable_unsafe_install: true
          EOF
          
      - name: Install Arduino cores
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
      
      - name: Install OneWire library
        run: |
          arduino-cli lib install OneWire
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      
      - name: Install Arduino CI
        run: |
          gem install arduino_ci -v 1.6.2
      
      - name: Create mock AVR include structure
        run: |
          sudo mkdir -p /usr/include/avr/util
          sudo cp /usr/lib/avr/include/util/crc16.h /usr/include/avr/util/
      
      - name: Run Arduino CI Tests
        run: |
          CPLUS_INCLUDE_PATH=/usr/lib/avr/include:$CPLUS_INCLUDE_PATH arduino_ci.rb