name: Arduino CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  runTest:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 1.5: Debug .arduino-ci.yml
      - name: Debug .arduino-ci.yml
        run: |
          cat .arduino-ci.yml        

      # Step 2: Install Arduino CLI
      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sudo sh

      # Step 3: Add Arduino CLI to PATH
      - name: Add Arduino CLI to PATH
        run: |
          echo "/home/runner/work/Arduino-Temperature-Control-Library/Arduino-Temperature-Control-Library/bin" >> $GITHUB_PATH

      # Step 4: Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      # Step 5: Install Arduino CI gem
      - name: Install Arduino CI
        run: |
          gem install arduino_ci -v 1.5.0

      # Step 6: Install OneWire Library
      - name: Install OneWire Library
        run: |
          arduino-cli lib install "OneWire"

      - name: Debug .arduino-ci.yml Configuration and Arduino Setup
        run: |
          arduino-cli core list
          arduino-cli lib list
          cat .arduino-ci.yml
        

      # Step 7: Run Arduino CI tests
      - name: Run Arduino CI Tests
        run: |
          arduino_ci.rb
